server { # simple reverse-proxy
  listen       1186;
  server_name  localhost;

  # pass requests for dynamic content to rails/turbogears/zope, et al
  location / {
    proxy_set_header Host $host:$server_port;
    proxy_set_header X-Real-IP  $remote_addr;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_set_header X-Forwarded-Proto $scheme;

    proxy_pass      http://redmine:3000;
  }
}
