services:
  db-next:
    image: postgres:$POSTGRES_MAJOR-alpine
    restart: unless-stopped
    volumes:
      - ./data/next/db:/var/lib/postgresql/data:Z
    environment:
      - POSTGRES_PASSWORD=$NEXT_POSTGRES_PASSWORD
      - POSTGRES_DB=$NEXT_POSTGRES_DB
      - POSTGRES_USER=$NEXT_POSTGRES_USER
    deploy:
      resources:
        limits:
          cpus: '0.20'
          memory: 200M
        reservations:
          memory: 150M
    healthcheck:
      test: ["CMD-SHELL", "sh -c 'pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB}'"]
      interval: 5s
      timeout: 3s
      retries: 5
    networks:
      next-backend:
        aliases:
          - db

  # Needs to install apps
  # docker-compose exec -u www-data next ./occ app:install groupfolders
  # Also requires enabling access to nginx user
  # and also specifying the directory as good for the server to look inside
  # semanage fcontext -a -t httpd_sys_content_t "/srv/static/next(/.*)?"
  # restorecon -Rv /srv/static/next
  next-common: &next-common
    image: nextcloud:29-fpm
    volumes:
      - ./data/next/data/html:/var/www/html:z
      - ./data/next/data/html:/srv/static/next:z
      - ./data/next/data/data:/var/www/html/data:Z
      - ./provision.sh:/usr/local/lib/provision.sh
    environment:
      - POSTGRES_PASSWORD=$NEXT_POSTGRES_PASSWORD
      - POSTGRES_DB=$NEXT_POSTGRES_DB
      - POSTGRES_USER=$NEXT_POSTGRES_USER
      - POSTGRES_HOST=db

      - NEXTCLOUD_ADMIN_USER=$ADMIN_USERNAME
      - NEXTCLOUD_ADMIN_PASSWORD=$ADMIN_PASSWORD
      - NEXTCLOUD_TRUSTED_DOMAINS=$NEXT_HOSTNAME.$DOMAINNAME $NEXT_HOSTNAME

      - LDAP_READER_DN=$LDAP_READER_DN
      - LDAP_READER_PASSWORD=$LDAP_READER_PASSWORD
    deploy:
      resources:
        limits:
          cpus: '0.30'
          memory: 300M
        reservations:
          memory: 150M
    healthcheck:
      test: ["CMD-SHELL", "su -l www-data -s /usr/local/bin/php /var/www/html/occ status 2>/dev/null | grep -e 'installed: true' -e 'maintenance: false' -e 'needsDbUpgrade: false' | wc -l | [ `cat` = 3 ]"]
      interval: 30s
      timeout: 10s
      retries: 5
    networks:
      - next-backend
      - ldap-backend

  next:
    <<: *next-common
    depends_on:
      db-next:
        condition: service_healthy
      # TODO this might belong to next-init.depends_on
      ldap-config-acl:
        condition: service_completed_successfully

  next-init:
    <<: *next-common
    entrypoint: >
      bash -c '
        . /usr/local/lib/provision.sh
        configure_nextcloud
        configure_nextcloud_ldap
        '
    depends_on:
      next:
        condition: service_healthy

  gateway:
    image: nginx:stable
    ports:
      - "1181:1181"
      - "1182:1182"
      - "1183:1183"
      - "1184:1184"
      - "1185:1185"
      - "1186:1186"
    volumes:
      - ./data/next/data/html:/srv/static/next:ro,z
      - ./data/gateway/conf.d:/etc/nginx/conf.d:ro,Z
    depends_on:
      bureau:
        condition: service_healthy
      keycloak-config:
        condition: service_completed_successfully
      next:
        condition: service_healthy
      phpldapadmin:
        condition: service_started
      redmine:
        condition: service_healthy
      rocketchat:
        condition: service_started
    deploy:
      resources:
        limits:
          cpus: '0.10'
          memory: 60M
        reservations:
          memory: 50M
    networks:
      - next-backend
      - ldap-backend
      - rocket-backend
      - keycloak-backend
      - redmine-backend

  mongo-rocket:
    image: mongo:6.0
    volumes:
      - ./data/rocket/mongo:/data/db:Z
    restart: unless-stopped
    command: mongod --oplogSize 128 --replSet rs0 --storageEngine=wiredTiger --bind_ip localhost,db
    security_opt:
      - "seccomp=unconfined"
    labels:
      - "traefik.enable=false"
    deploy:
      resources:
        limits:
          cpus: '0.40'
          memory: 500M
        reservations:
          memory: 400M
    healthcheck:
      test: ["CMD-SHELL", "mongosh --eval 'db.adminCommand(\"ping\")' --quiet || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      rocket-backend:
        aliases:
          - db

  mongo-init-rs:
    image: mongo:6
    depends_on:
      mongo-rocket:
        condition: service_healthy
    entrypoint: >
      bash -c '
      until mongosh --host mongo-rocket --quiet --eval "rs.status().ok" ||
            mongosh --host mongo-rocket --quiet --eval "rs.initiate({
                _id: \"rs0\",
                members: [{ _id: 0, host: \"mongo-rocket:27017\" }]
            }).ok
      "; do
        sleep 2
      done
      '
    networks:
      - rocket-backend

  rocketchat:
    image: rocket.chat:6.0
    volumes:
      - ./data/rocket/uploads:/app/bundle/programs/server/uploads/:Z
    environment:
      - ROOT_URL=http://localhost:1182
      - MONGO_URL=mongodb://db:27017/rocketchat?replicaSet=rs0&directConnection=true
      - MONGO_OPLOG_URL=mongodb://db:27017/local?replicaSet=rs0&directConnection=true

      - PORT=3000

      - ADMIN_USERNAME=$ROCKET_ADMIN_USERNAME
      - ADMIN_PASS=$ADMIN_PASSWORD
      - Accounts_UseDNSDomainCheck=false
      - OVERWRITE_SETTING_Show_Setup_Wizard=completed
    command: bash -c 'for i in `seq 1 30`; do node main.js && s=$$? && break || s=$$?; echo "Tried $$i times. Waiting 5 secs..."; sleep 5; done; (exit $$s)'
    depends_on:
      ldap-config-acl:
        condition: service_completed_successfully
      mongo-init-rs:
        condition: service_completed_successfully
    deploy:
      resources:
        limits:
          cpus: '0.90'
          memory: 1G
        reservations:
          memory: 900M
    networks:
      - ldap-backend
      - rocket-backend
    labels:
      - "traefik.backend=rocket"
      - "traefik.frontend.rule=Host: rocket.$DOMAINNAME"


  openldap:
    image: osixia/openldap
    # command: "--loglevel debug"
    # command: --copy-service
    ports:
      - "1389:389"
    environment:
      LDAP_TLS: 'false'
      LDAP_ORGANISATION: "The Enterprisey Intranet"
      LDAP_DOMAIN: "$DOMAINNAME"
      LDAP_BASE_DN: "$LDAP_BASE_DN"
      LDAP_ADMIN_PASSWORD: "$ADMIN_PASSWORD"
      LDAP_LOG_LEVEL: "256"
    volumes:
      - ./data/ldap/data:/var/lib/ldap:Z
      - ./data/ldap/slapd.d:/etc/ldap/slapd.d:Z
      - ./ldap-health-check.sh:/usr/local/bin/ldap-health-check.sh
    deploy:
      resources:
        limits:
          cpus: '0.10'
          memory: 80M
        reservations:
          memory: 50M
    healthcheck:
      test: [ "CMD", "/usr/local/bin/ldap-health-check.sh" ]
    networks:
      ldap-backend:
        aliases:
          - ldap

  ldap-config-acl:
    image: entint/openldap
    volumes:
      - ./provision.sh:/usr/local/lib/provision.sh
    depends_on:
      openldap:
        condition: service_healthy
    entrypoint: >
      bash -c '
      . /usr/local/lib/provision.sh
      configure_ldap_acl
      '

  phpldapadmin:
    image: osixia/phpldapadmin
    environment:
      PHPLDAPADMIN_LDAP_HOSTS: "openldap"
      PHPLDAPADMIN_HTTPS=false:
    depends_on:
      ldap-config-acl:
        condition: service_completed_successfully
    deploy:
      resources:
        limits:
          cpus: '0.10'
          memory: 80M
        reservations:
          memory: 50M
    networks:
      - ldap-backend

  db-keycloak:
    image: postgres:$POSTGRES_MAJOR-alpine
    volumes:
      - ./data/keycloak/db:/var/lib/postgresql/data:Z
    environment:
      - POSTGRES_PASSWORD=$KEYCLOAK_POSTGRES_PASSWORD
      - POSTGRES_DB=$KEYCLOAK_POSTGRES_DB
      - POSTGRES_USER=$KEYCLOAK_POSTGRES_USER
    networks:
      keycloak-backend:
        aliases:
          - db
    healthcheck:
      test: ["CMD-SHELL", "sh -c 'pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB}'"]
      interval: 5s
      timeout: 3s
      retries: 5
    deploy:
      resources:
        limits:
          cpus: '0.20'
          memory: 200M
        reservations:
          memory: 150M

  keycloak:
    image: entint/keycloak
    build:
      context: build/keycloak
    command:
      start --optimized --log-level=INFO
    security_opt:
      - "seccomp=unconfined"
    environment:
      - KC_DB_URL=jdbc:postgresql://db:5432/$KEYCLOAK_POSTGRES_DB
      - KC_DB_USERNAME=$KEYCLOAK_POSTGRES_USER
      - KC_DB_PASSWORD=$KEYCLOAK_POSTGRES_PASSWORD
      - KC_HOSTNAME=http://localhost:1184
      - KC_PROXY_HEADERS=xforwarded
      - KC_HTTP_ENABLED=true
      - DB_VENDOR=postgres
      - KC_BOOTSTRAP_ADMIN_USERNAME=$ADMIN_USERNAME
      - KC_BOOTSTRAP_ADMIN_PASSWORD=$ADMIN_PASSWORD

      - LDAP_READER_PASSWORD=$LDAP_READER_PASSWORD

    depends_on:
      db-keycloak:
        condition: service_healthy
      ldap-config-acl:
        condition: service_completed_successfully
    deploy:
      resources:
        limits:
          cpus: '2.60'
          memory: 1650M
        reservations:
          memory: 1550M
    healthcheck:
      test: ["CMD-SHELL", "curl --head -fsS http://localhost:9000/health/ready"]
      interval: 10s
      timeout: 3s
      retries: 10
    networks:
      - ldap-backend
      - keycloak-backend

  keycloak-config:
    image: entint/keycloak
    volumes:
      - ./provision.sh:/usr/local/lib/provision.sh
    depends_on:
      keycloak:
        condition: service_healthy
    entrypoint: >
      bash -c '
      . /usr/local/lib/provision.sh
      configure_keycloak_next
      configure_keycloak_bureau
      configure_keycloak_ldap
      configure_keycloak_rocketchat
      configure_keycloak_redmine
      '

  bureau:
    image: entint/bureau
    build:
      # TODO the same as below
      context: ../../bureau
    depends_on:
      - rocketchat
      - phpldapadmin
    environment:
      - NEXTCLOUD_PASSWORD=$ADMIN_PASSWORD
      - NEXTCLOUD_HOST=http://gateway:1181
      - NEXTCLOUD_USER=$ADMIN_USERNAME

      - ROCKETCHAT_HOST=http://rocketchat:3000
      - ROCKETCHAT_PASSWORD=$ADMIN_PASSWORD
      - ROCKETCHAT_USER=$ROCKET_ADMIN_USERNAME

      - EDAP_HOSTNAME=ldap:389
      - EDAP_PASSWORD=$ADMIN_PASSWORD
      - EDAP_DOMAIN=$DOMAINNAME
      - LDAP_READER_PASSWORD=$LDAP_READER_PASSWORD
      - EDAP_USER=cn=admin

      - SAML_PATH=/app/saml
    volumes:
      - ./data/bureau/env:/app/.env:Z
      - ./data/bureau/ldap.ini:/app/ldap.ini:Z
      - ./data/bureau/settings.json:/app/saml/settings.json:Z
      # TODO bureau should be submodule of intranet or vice versa.
      # ../../bureau/bureau breaks when the repo is in unexpected folder.
      - ../../bureau/bureau:/app/bureau:Z
    security_opt:
      - "seccomp=unconfined"
    healthcheck:
      test: ["CMD-SHELL", "curl -s -o /dev/null http://localhost:8080 || exit 1"]
      interval: 5s
      timeout: 3s
      retries: 5
    networks:
      - ldap-backend
      - keycloak-backend
      - next-backend
      - rocket-backend

  redmine-gen-samlconf:
    build:
      context: build/gen-conf
    volumes:
      - ./provision.sh:/usr/local/lib/provision.sh
      - ./data/redmine/config:/redmine-saml-config
    entrypoint: >
      bash -c '
      . /usr/local/lib/provision.sh
      configure_redmine_saml > /redmine-saml-config/saml.rb
      '

  redmine:
    image: entint/redmine
    build:
      context: build/redmine
    entrypoint: ["/usr/local/bin/redmine-entrypoint.sh"]
    command: ["rails", "server", "-b", "0.0.0.0"]
    depends_on:
      ldap-config-acl:
        condition: service_completed_successfully
      redmine-gen-samlconf:
        condition: service_completed_successfully
      db-redmine:
        condition: service_healthy
    environment:
      - REDMINE_DB_POSTGRES=db
      - REDMINE_DB_USERNAME=$REDMINE_POSTGRES_USER
      - REDMINE_DB_PASSWORD=$REDMINE_POSTGRES_PASSWORD
      - REDMINE_DB_DATABASE=$REDMINE_POSTGRES_DB
      - REDMINE_PLUGINS_MIGRATE=true
      - SECRET_KEY_BASE=$REDMINE_SECRET
    volumes:
      - ./data/redmine/files:/usr/src/redmine/files:Z
      - ./data/redmine/config/saml.rb:/usr/src/redmine/config/initializers/saml.rb:Z
      - ./redmine-entrypoint.sh:/usr/local/bin/redmine-entrypoint.sh
    security_opt:
      - "seccomp=unconfined"
    healthcheck:
      test: ["CMD-SHELL", "curl --fail http://localhost:3000/ || exit 1"]
      interval: 30s
      timeout: 5s
      retries: 3
      start_period: 20s

    networks:
      - redmine-backend
      - ldap-backend


  db-redmine:
    image: postgres:14-alpine
    environment:
      - POSTGRES_USER=$REDMINE_POSTGRES_USER
      - POSTGRES_PASSWORD=$REDMINE_POSTGRES_PASSWORD
      - POSTGRES_DB=$REDMINE_POSTGRES_DB
    volumes:
      - ./data/redmine/db:/var/lib/postgresql/data:Z
    deploy:
      resources:
        limits:
          cpus: '0.20'
          memory: 200M
        reservations:
          memory: 150M
    healthcheck:
      test: ["CMD-SHELL", "sh -c 'pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB}'"]
      interval: 5s
      timeout: 3s
      retries: 5
    networks:
      redmine-backend:
        aliases:
          - db

# Custom network so all services can communicate using a FQDN
networks:
  keycloak-backend:
  next-backend:
  rocket-backend:
  redmine-backend:
  ldap-backend:
